### ISSUE TITLE
Install instructions use plain http

### ISSUE THREAD

**Issue by rubenv** [ElasticBox/elastickube#1]
On the main page:

```
curl -s elastickube.com | bash
```

I know this looks pretty, but it's a ridiculously bad idea to advise people to pipe the output of a webpage to bash, especially when served over plain HTTP.

Please, for the safety of your users, at least use HTTPS.

**Comment by albertoarias** [comment]
@rubenv Thanks for the feedback.

I updated the README and our page to add https.
