### ISSUE TITLE
502 on https://elastickube.com/

### ISSUE THREAD

**Issue by edouardKaiser** [ElasticBox/elastickube#121]
It looks like https://elastickube.com/ is down, I get an HTTP 502.
Is this project still maintained ?

**Comment by albertoarias** [comment]
Yes it is. We will release a roadmap soon.

Where are you connecting from? It seems to be working from my location.

**Comment by edouardKaiser** [comment]
I'm in Sydney, Australia. Looks like it's working now, wrong alert, thanks for the response :)

**Comment by albertoarias** [comment]
It seems we had a glitch at some point. Let me know how it goes.
