### ISSUE TITLE
Heapster Connection

### ISSUE THREAD

**Issue by jhelblingHH** [ElasticBox/elastickube#134]
Heapster Connection
HTTP 503: Service Unavailable

**Comment by gsanchezu** [comment]
Hi Johann, could you please provide some additional background for your issue?
For example, is it a new environment, or an issue that just appeared in an existing installation? What were you trying to accomplish?
Could you also please provide any significant related logs to troubleshoot? 
Thanks!

**Comment by jhelblingHH** [comment]
Hi thanks. Was fixed. Heapster was not really up and running. New deploy was helpfully
