### ISSUE TITLE
Unable to install elastickube

### ISSUE THREAD

**Issue by ianwalter** [ElasticBox/elastickube#18]
I set up Kubernetes locally on OS X using [kube-solo-osx](https://github.com/TheNewNormal/kube-solo-osx) and it's running at http://192.168.64.2:8080 however the install command fails to verify the Kubernetes cluster:
```
curl -s https://elastickube.com | bash -s -- -u http://192.168.64.2:8080
```
I get this when getting services:
```
kubectl --server=http://192.168.64.2:8080 get svc
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   10.100.0.1   <none>        443/TCP   <none>     27m
```
But it shows a different list of services when running the command with `--namespace=kube-system` is this why it's not working?

**Comment by albertoarias** [comment]
@ianwalter our install script uses kubectl internally but it does not specify the --server parameter. We rely on kubectl to be preconfigured to talk to the target cluster.

Can you try configuring the context of kubectl?
https://coreos.com/kubernetes/docs/1.0.3/configure-kubectl.html

We could add the server option to the install script. I am just not sure if this is a common use case. What do you think?

**Comment by ianwalter** [comment]
Configuring kubectl worked for me so I guess it's not necessary. Thanks!
