### ISSUE TITLE
Edit function of namespace screen displays an error

### ISSUE THREAD

**Issue by mdbishop** [ElasticBox/elastickube#21]
On a fresh install, admin -> namespaces, clicking edit on a namespace displays:

```
Cannot read property 'close' of undefined
```

No messages show in the javascript console and nothing apparent appeared on a cursory look at the server side logs.

**Comment by paulino-corujo** [comment]
@mdbishop thank you for reporting this bug, I have sent a PR to fix it that is already merged (https://github.com/ElasticBox/elastickube/pull/23)

**Comment by arnaud-elasticbox** [comment]
@mdbishop we have released a new version which includes a fix for this. Thanks for reporting it.

**Comment by mdbishop** [comment]
@arnaud-elasticbox Wow you guys are fast, thank YOU!  Excited to give today's batch of fixes a go.

**Comment by mdbishop** [comment]
@paulino-corujo @arnaud-elasticbox  #23 did the trick, thank you sirs!
