### ISSUE TITLE
Feature Request: Allow searching by more than name field on Instances screen

### ISSUE THREAD

**Issue by mdbishop** [ElasticBox/elastickube#26]
I'd love to be able to filter just failed instances, for instance, to I can delete them and their cruft from the system (or at least from my screen).  The search seems to take only the name into consideration at this point.  I'm sure this will expand to labels as well, but one request at a time. :smile:

**Comment by manolakis** [comment]
Hello @mdbishop. Yesterday we merged the capability to filter by the pod status, so now you should be able to delete all your failed instances easily :)

![filters](https://cloud.githubusercontent.com/assets/329771/15368169/b362f2ca-1d2c-11e6-9122-a07b02d0d582.png)

As the feature request is implemented I'm going to close this.

Best
