### ISSUE TITLE
Unable to setup elastickube on CentOS 7

### ISSUE THREAD

**Issue by surajssd** [ElasticBox/elastickube#33]
Tried setting up ElasticKube
```bash
[vagrant@centos7-adb ~]$ curl -s https://elastickube.com | bash
  _____ _           _   _      _  __     _
 | ____| | __ _ ___| |_(_) ___| |/ /   _| |__   ___
 |  _| | |/ _` / __| __| |/ __| ' / | | | '_ \ / _ \
 | |___| | (_| \__ \ |_| | (__| . \ |_| | |_) |  __/
 |_____|_|\__,_|___/\__|_|\___|_|\_\__,_|_.__/ \___| by ElasticBox

Checking kubectl is available           [ ✓ ]
Verifying Kubernetes cluster            [ ✓ ]
Setting up elastickube-server svc       [ FAILED ]
```

Also tried using `sudo`
```bash
[vagrant@centos7-adb ~]$ curl -s https://elastickube.com | sudo bash
  _____ _           _   _      _  __     _
 | ____| | __ _ ___| |_(_) ___| |/ /   _| |__   ___
 |  _| | |/ _` / __| __| |/ __| ' / | | | '_ \ / _ \
 | |___| | (_| \__ \ |_| | (__| . \ |_| | |_) |  __/
 |_____|_|\__,_|___/\__|_|\___|_|\_\__,_|_.__/ \___| by ElasticBox

Checking kubectl is available           [ ✓ ]
Verifying Kubernetes cluster            [ ✓ ]
Setting up elastickube-server svc       [ FAILED ]
```

I am running [CentOS 7 ADB Vagrant box](https://atlas.hashicorp.com/projectatomic/boxes/adb/versions/1.7.2) and Kubernetes is setup using [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-k8s-singlenode-setup). What other information do you need about my environment? Please help me with what am I missing?

**Comment by albertoarias** [comment]
@surajssd I just deployed the Vagrantfile. Atomic is a heavy modified kubernetes. For ElasticKube to work we the following things:
- kube-system namespace
- access to the kube-apiserver endpoint (secured or unsecured)
- for metrics we require having heapster running

First create the kube-system namespace:

`kubectl create -f - << NAMESPACE
kind: "Namespace"
apiVersion: "v1"
metadata:
  name: "kube-system"
  labels:
    name: "kube-system"
NAMESPACE`

Then the install command `curl -s https://elastickube.com | bash` ALMOST works 

The problem that I am facing is that somehow the secrets file cannot be read from within the container:
/var/run/secrets/kubernetes.io/serviceaccount/token

See here:
https://github.com/openshift/origin/issues/6981

It seems they fixed the issue in Openshift RC4

**Comment by albertoarias** [comment]
@surajssd disabling SELinux fixes the problem
`setenforce 0`

Then I recreated the elastickube-server replication controller by deleting the it and reinstalling:
`kubectl --namespace=kube-system delete rc elastickube-server`
`curl -s https://elastickube.com | bash`

Finally to test everything was working I created a reverse tunnel:
`ssh vagrant@<ip address of the vm> -L 9000:localhost:8080`
(I got the ip address using the `ip addr` command within the VM)

And then open a browser in your machine and load http://localhost:9000/api/v1/proxy/namespaces/kube-system/services/elastickube-server

**Comment by surajssd** [comment]
@albertoarias Thanks a lot for the steps and help, I appreciate that.

In the above VM I followed these steps
```bash
sudo setenforce 0
cat >> namespace.yaml<<NAMESPACE
kind: "Namespace"
apiVersion: "v1"
metadata:
  name: "kube-system"
  labels:
    name: "kube-system"
NAMESPACE

kubectl create -f namespace.yaml
curl -s https://elastickube.com | bash

# note the IP address at the end of the above command
# note IP address of this VM

ip a sh eth0
```
Open new-terminal and do:
`ssh -L 9898:10.254.177.213:80 vagrant@192.168.121.24`
OR
`ssh -L <some-port>:<IP-address-from-output>:80 vagrant@<IP-address-of-VM>`
password: `vagrant`

Open Browser and goto: `localhost:9898`

Also I would like this to see working with SELINUX enabled, to ensure security.

**Comment by surajssd** [comment]
Please tell me how do I deploy an app, which has custom built containers in it. I have Kubernetes artifacts for it. Should i directly use the `kubectl create -f <files>` ?
https://github.com/surajssd/docker-birthday-3/tree/master/k8s-artifacts

**Comment by albertoarias** [comment]
@surajssd We adopted the helm standard to package apps for kubernetes:
http://helm.readthedocs.org/en/latest/authoring_charts/

You need to create the chart and then point your elastickube to the github repo containing the chart. ElasticKube will pull that repo and automatically sync the database of charts so you an deploy from the UI.

FYI, we are working on putting the documentation out.

**Comment by surajssd** [comment]
Thats awesome! :) I will look into the making helm charts. Thanks for all the information, that was very nice of you, if you want you can close this issue.
