### ISSUE TITLE
 Failed for reason PodExceedsFreeMemory and possibly others

### ISSUE THREAD

**Issue by miko-code** [ElasticBox/elastickube#50]
Hi ,
Im trying to run elestickube but i getting this error on **elastickube-server**  service.

Im using single node core os , and i can run k8 .

Any suggestions how to solve it ?

**Comment by albertoarias** [comment]
@miko-code I think you forgot to paste the error message

**Comment by albertoarias** [comment]
@miko-code Somebody just pointed out to me that the error message is on the title. It seems like you don't have enough free memory in your cluster. You can download the script from `curl elastickube.com -o install.sh` and remove the limits from the resource controller. (They are embedded within the script)

Though you should try to run it in a cluster with more free resources. Let me know if that works.

**Comment by miko-code** [comment]
@albertoarias  adding more memory to the machine solve the problem.
i change the host port to 8088 because k8 is ruining on port 80.
Now im getting 
`Failed to create docker container with error: no such image
`

**Comment by albertoarias** [comment]
@miko-code What is your default docker registry? Our images are hosted in docker hub. We are considering pushing them to gcr.io too

**Comment by davisein** [comment]
@miko-code The issue seems related with #54. Can you try now again? Sorry for the inconvenience
