### ISSUE TITLE
Unable to create first user

### ISSUE THREAD

**Issue by jcderr** [ElasticBox/elastickube#6]
I've deployed elastickube into my cluster and can access the initial signup page. When I fill in the form, nothing happens. My chrome console shows the following:

```
WebSocket connection to 'ws://<<hostname>>/api/v1/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
angular.js:12722TypeError: Cannot read property 'status' of undefined
    at ek-signup.controller.js:37
    at l (angular.js:14991)
    at angular.js:15007
    at h.$eval (angular.js:16251)
    at h.$digest (angular.js:16069)
    at angular.js:16290
    at i (angular.js:5729)
    at angular.js:6006(anonymous function) @ angular.js:12722
```

**Comment by jcderr** [comment]
Changing my AWS ELB to use TCP instead of HTTP resulted in it getting further, but still failing.

```
angular.js:12722 TypeError: Cannot read property 'metadata' of undefined
    at e.a.value (session-action-creator.service.js:42)
    at initialization.service.js:76
    at l (angular.js:14991)
    at angular.js:15007
    at h.$eval (angular.js:16251)
    at h.$digest (angular.js:16069)
    at h.$apply (angular.js:16359)
    at WebSocket._.isUndefined._websocket.readyState.WebSocket.CLOSED._websocket.onmessage (websocket-client.service.js:60)
```

**Comment by arnaud-elasticbox** [comment]
We think it is a connection issue between the ui and the backend container "elastickube-api". Can you send us the log of the "elastickube-api" container? 

You can get the log using the kubectl logs command.

**Comment by albertoarias** [comment]
@jcderr I think I have seen this error when the kube-dns service is not configured. Which means that the api and charts service cannot connect the mongo service.

**Comment by jcderr** [comment]
Looks like there's a tornado exception in here.

Cluster DNS _is_ working. I use it pretty extensively in my setup.

[elastickube_error.log.zip](https://github.com/ElasticBox/elastickube/files/179044/elastickube_error.log.zip)

**Comment by arnaud-elasticbox** [comment]
I managed to reproduce. We are reading a token from this location /var/run/secrets/kubernetes.io/serviceaccount/token to access the Kubernetes API and in your case, we are failing to authenticate using this token. Do you have any idea why this token is invalid?

**Comment by jcderr** [comment]
I'm storing all of my keys, etc, in `/etc/kubernetes/ssl` ... can we make this variable?

**Comment by arnaud-elasticbox** [comment]
Yes, it makes total sense. Thanks for the update, I will send a pull request.

**Comment by jcderr** [comment]
I misinterpreted this as a path on the host filesystem. That file is available in my container, but looking at my kubeapiserver logs, it appears this certificate may be malformed. I'll take a look at that, as well.

**Comment by albertoarias** [comment]
@jcderr I just pushed an update that allows you to use the unsecure port (like kube-dns typically does)

Can you try redeploying?
