### ISSUE TITLE
ElasticKube looking for hardcoded kube-dns-v9

### ISSUE THREAD

**Issue by JamieAP** [ElasticBox/elastickube#61]
As shown here: http://puu.sh/orCqB/dad1e8dd3b.png

ElasticKube is looking for a (I think) hardcoded kube-dns-v9, whereas out of the box deployments are using v11.

**Comment by davisein** [comment]
We are looking on how to make the search more general, supporting any version and DNS server.

This only affects to the Diagnostics page as the rest of the application doesn't try to detect the status of the DNS.
I'll investigate how to make it more general. @JamieAP Do you have any suggestion?

**Comment by davisein** [comment]
@JamieAP I have opened a PR #62 for this.

The approach is to check for the kubernetes.default domain which must be provided by the DNS system according to their documentation. [https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/addons/dns/README.md#3-validate-dns-works]

Let us know if you find any problem with the new approach

**Comment by JamieAP** [comment]
@davisein Perfect, thank you!
