### ISSUE TITLE
 Internet Connection Requesting "http://google.com" failed: "[Errno -2] Name or service not known".

### ISSUE THREAD

**Issue by madhu25** [ElasticBox/elastickube#78]
Got the following error on diagnostics page:

Internet Connection
Requesting "http://google.com" failed: "[Errno -2] Name or service not known".

**Comment by davisein** [comment]
Hi @madhu25,

It seems that you don't have access to the internet or a working DNS from your ElasticKube. 
The Name or service not known points to a DNS configuration issue.

Could you ensure that you have access to the internet and a working DNS accessible from the pod?

For some of the features of ElasticKube (most notably, syncing with Charts from public repositories like the default one) you need access to the internet. The diagnosis page checks that to help you fix the issue.

Let me know if that helped or you have further questions.

**Comment by madhu25** [comment]
Yes thanks .
