### ISSUE TITLE
Any way to deploy to on-premise?

### ISSUE THREAD

**Issue by bh016088** [ElasticBox/elastickube#8]
I run an on-premise Kubernetes cluster and my developers would love the ability to use ElasticKube.  I have tried creating the elastickube-server service with NodePort instead of LoadBalancer and can get to the first login page but then I just receive "Forbidden" over and over again.

Any tips or suggestions?

**Comment by albertoarias** [comment]
Every Kubernetes environment is a little bit different. Can you provide some details about the environment?

Also can you clarify where are you getting the Forbidden message?

**Comment by albertoarias** [comment]
@bh016088 Is the forbidden message coming from the logs of the container or from the UI?
Check this out:
https://github.com/ElasticBox/elastickube/issues/6

**Comment by bh016088** [comment]
The forbidden message is coming from the UI.  My cluster dns is working as expected.  I looked at that 

My kubernetes environment is running on Centos 7, Docker 1.9.1, Kube 1.1.4.  

I also have a "tornado" error as in #6 

http://pastebin.com/raw/2a0MqX5t

**Comment by albertoarias** [comment]
@bh016088 I fixed a couple of things that I think might help with your deployment. Check this out:
https://github.com/ElasticBox/elastickube/issues/11

**Comment by bh016088** [comment]
Now, when signing up for the admin user I get the following on the UI:

> Cannot read property 'metadata' of undefined

Checked the apiserver container and got the following:

> ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f91945e5470>
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
>     ret = callback()
>   File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 615, in <lambda>
>     self.add_future(ret, lambda f: f.result())
>   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/elastickube/api/v1/__init__.py", line 62, in initialize
>     yield settings["kube"].build_resources()
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/elastickube/api/kube/client.py", line 231, in build_resources
>     api_versions_response = yield self.http_client.get("/api")
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/elastickube/api/kube/client.py", line 96, in get
>     result = yield client.fetch(url, method="GET", headers=self.build_headers())
>   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
> CurlError: HTTP 599: Could not resolve host: https

**Comment by bh016088** [comment]
Upon subsequent attempts at going to the dashboard I am prompted with a login.  When I enter the credentials of the admin user I get:

> Cannot read property 'statusText' of undefined

**Comment by bh016088** [comment]
Just tested redeploying with the following command:
`curl -s https://elastickube.com | bash -s -- -u http://<kube-apiserver>:8080`

And I got through!  I will poke around and close if fixed.

**Comment by albertoarias** [comment]
@bh016088 Great!

I was about to send you a note that we made a commit that fixes some issues related to the install. We are also going to work in a diagnostics page, it should make it easier to figure out how to address this config issues.

Looking forward to your feedback. Also you can check out what is coming next here: 
http://pt.slideshare.net/albertoariasmaestro/elastickube
