### ISSUE TITLE
Explanation of Charts

### ISSUE THREAD

**Issue by masondesu** [ElasticBox/elastickube#88]
Hey there. Thanks for building this, it's great to have some additional visualizations for our cluster. I can't seem to find anywhere in the repo or the marketing site about what charts actually are and/or how they're supposed to work or be used.

Can you point to some resources on how these are intended to be used?

**Comment by davisein** [comment]
Hi @masondesu,

The charts refer to Helm charts (see https://helm.sh/). Here is the repository with charts that we use as an example: https://github.com/helm/charts. It's a great starting point with a nice catalog of Charts.

There are lots of changes in the community, making helm part of the Kubernetes community here: https://github.com/kubernetes/helm.

Let us know if you have more doubts.
