### ISSUE TITLE
Help setting up Google Auth

### ISSUE THREAD

**Issue by oO-Zam** [ElasticBox/elastickube#9]
Some basic documentation would be great. is this SASL/SAML? oAuth? some API Key thing? help.

**Comment by albertoarias** [comment]
Is on the top of our list to get some documentation out.

Currently there is only support for google apps authentication. For that you need to create your own set of OpenID credentials on the google developer console:

https://developers.google.com/identity/protocols/OpenIDConnect#getcredentials

Use those credentials on the Admin page and your good to go.

**Comment by albertoarias** [comment]
@oO-Zam Did you manage to make it work?
