### ISSUE TITLE
Make the bringup script easier to inspect casually

### ISSUE THREAD

**Issue by colemickens** [ElasticBox/elastickube#98]
I really don't feel comfortable piping something into bash, especially when it's going to start using `kubectl` to do stuff to my cluster and the README isn't precise enough about what is going to happen when I run that command. Worse, it seems like you're doing some sort of UA sniffing or something and over loading the https://elastickube.com URL for serving the script. Which means that there are even more hoops for me to jump through just to peak at the script.

Can you just make a plain old link to the script really obvious? I'm fairly curious so I'm going to go pull the script with curl, but maybe others wouldn't bother....

**Comment by arnaud-elasticbox** [comment]
@colemickens it you run curl https://elastickube.com it should output the script but I agree, we could have an obvious link to read the script into a browser instead of curl

**Comment by albertoarias** [comment]
@colemickens The script is also part of the repo. We tried to make it easy to read.

https://github.com/ElasticBox/elastickube/blob/master/build/deploy.sh

**Comment by colemickens** [comment]
Cool. Maybe just a link to it on the README? (For example does elastickube.com + curl redirect to github [master branch?], or is there another copy of the script somewhere?)

**Comment by albertoarias** [comment]
Make sense, I sent a PR to update the README. The file comes from the repo, we cache it on the website.
